# Generated by Django 5.1.3 on 2024-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
